name: مكتب ندر الرقمي

on: workflow_dispatch

jobs:
  تشغيل_الجهاز:
    runs-on: windows-latest

    steps:
    - name: 🛠 تحميل برنامج Getscreen
      run: |
        Invoke-WebRequest -Uri "https://app.getscreen.me/downloads/windows" -OutFile "agent.exe"
        Start-Process "agent.exe" -ArgumentList "/email nader@email.com"

    - name: ✅ تأكيد الربط
      run: echo "🎭 تم تثبيت برنامج Getscreen وربط الجهاز بحساب ندر. المكتب الرقمي جاهز للتحكم."
